# ModelConfig
model_type: Hand3DActionTransformer
input_dim: 135 #109 #190
hidden_layers: 135
out_dim: 36
dropout: 0.0
dropout_att: 0.3
dropout_mlp: 0.0
trans_num_layers: 2
trans_num_heads: 3
seq_length: 20
load_checkpoint: True
checkpoint_path: '/caa/Homes01/wmucha/repos/hand_actions_recognition/checkpoints/royal-grass-174/checkpoint_best.pth'
# TrainingConfig
scheduler_milestones: [500, 700, 900, 1100]
seed_num: 42
max_epochs: 1000
batch_size: 64
device: 4
early_stopping: 500
emplying_objs: True
checkpoint_pth: 'checkpoints/20FPS_repeat'
#DataConfig
data_dir: '/data/wmucha/datasets/h2o_ego/h2o_ego'
annotation_train: '/caa/Homes01/wmucha/datasets/h2o_CASA'
data_for_model: ['hand_pose', "obj"]
data_dimension: 2D
no_of_input_frames: 20
hand_bb_flag: False
using_obj_bb: True
own_pose_flag: True
using_obj_label: True
hand_pose_type: 'gt_hand_pose'
obj_pose_type: 'GT'
apply_vanishing: True
vanishing_proability: 0.3
obj_to_vanish: 3
#OptimizerConfig
type: AdamW
lr: 1e-3
weight_decay: 1e-4
momentum: 0.0