# H2oHandsData:
path: '/data/wmucha/datasets'
imgs_path: 'h2o_ego/h2o_ego'
batch_size: 32
img_size: [512,512]
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
use_depth: True
depth_img_type: 'est_low'
segment_list: [0,700, 800,900,1000,1100,1200,1300,1400, 1500, 1600, 1700]
segment_list_val: [120]
# max_train_samples: 100
# max_val_samples: 100
# TrainingConfig:
experiment_name: '3DHPDSEG'
# debug: True
device: 5
lr: 0.5
max_epochs: 1000
early_stopping: 10
weight_decay: 0.0
momentum: 0.9
criterion: 'EffHandEgoNetLoss3D'
num_workers: 6
load_model: True
load_model_path: 'checkpoints/fluent-silence-280/checkpoint_best.pth'
model_type: 'EffHandEgoNet3D'
