# H2oHandsData:
path: '/data/wmucha/datasets'
imgs_path: 'h2o_ego/h2o_ego'
batch_size: 1
img_size: [512,512]
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
use_depth: True
depth_img_type: 'est_low'
segment_list: [0,120]
segment_list_val: [120]
# max_train_samples: 100
# max_val_samples: 100
# TrainingConfig:
seed: 37
experiment_name: '3DHPDSEG'
device: 7
lr: 0.1
max_epochs: 500
early_stopping: 13
weight_decay: 0.0
momentum: 0.9
criterion: 'EffHandEgoNetLoss3D'
num_workers: 6
load_model: False
load_model_path: 'checkpoints/peachy-waterfall-101/checkpoint_best.pth'
model_type: 'EffHandEgoNet3D'
debug: True
